package net.diemond_player.unidye.datagen;

import net.minecraft.data.PackOutput;
import net.minecraft.data.recipes.FinishedRecipe;
import net.minecraft.data.recipes.RecipeCategory;
import net.minecraft.data.recipes.RecipeProvider;
import net.minecraft.data.recipes.ShapedRecipeBuilder;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.ItemTags;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.Blocks;

import java.util.function.Consumer;

import static net.diemond_player.unidye.Unidye.MOD_ID;

public class UnidyeRecipeGenerator extends RecipeProvider {

    public UnidyeRecipeGenerator(PackOutput pOutput) {
        super(pOutput);
    }

    @Override
    protected void buildRecipes(Consumer<FinishedRecipe> pWriter) {
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.RED_WOOL, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL)
                .define('D', Items.RED_DYE)
                .unlockedBy("has_needed_dye", has(Items.RED_DYE))
                .group("wool_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.RED_WOOL) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.ORANGE_WOOL, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL)
                .define('D', Items.ORANGE_DYE)
                .unlockedBy("has_needed_dye", has(Items.ORANGE_DYE))
                .group("wool_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.ORANGE_WOOL) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.YELLOW_WOOL, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL)
                .define('D', Items.YELLOW_DYE)
                .unlockedBy("has_needed_dye", has(Items.YELLOW_DYE))
                .group("wool_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.YELLOW_WOOL) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.GREEN_WOOL, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL)
                .define('D', Items.GREEN_DYE)
                .unlockedBy("has_needed_dye", has(Items.GREEN_DYE))
                .group("wool_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.GREEN_WOOL) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.LIME_WOOL, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL)
                .define('D', Items.LIME_DYE)
                .unlockedBy("has_needed_dye", has(Items.LIME_DYE))
                .group("wool_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.LIME_WOOL) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.LIGHT_BLUE_WOOL, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL)
                .define('D', Items.LIGHT_BLUE_DYE)
                .unlockedBy("has_needed_dye", has(Items.LIGHT_BLUE_DYE))
                .group("wool_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.LIGHT_BLUE_WOOL) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.BLUE_WOOL, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL)
                .define('D', Items.BLUE_DYE)
                .unlockedBy("has_needed_dye", has(Items.BLUE_DYE))
                .group("wool_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.BLUE_WOOL) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.PURPLE_WOOL, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL)
                .define('D', Items.PURPLE_DYE)
                .unlockedBy("has_needed_dye", has(Items.PURPLE_DYE))
                .group("wool_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.PURPLE_WOOL) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.MAGENTA_WOOL, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL)
                .define('D', Items.MAGENTA_DYE)
                .unlockedBy("has_needed_dye", has(Items.MAGENTA_DYE))
                .group("wool_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.MAGENTA_WOOL) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.PINK_WOOL, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL)
                .define('D', Items.PINK_DYE)
                .unlockedBy("has_needed_dye", has(Items.PINK_DYE))
                .group("wool_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.PINK_WOOL) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.CYAN_WOOL, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL)
                .define('D', Items.CYAN_DYE)
                .unlockedBy("has_needed_dye", has(Items.CYAN_DYE))
                .group("wool_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.CYAN_WOOL) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.BROWN_WOOL, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL)
                .define('D', Items.BROWN_DYE)
                .unlockedBy("has_needed_dye", has(Items.BROWN_DYE))
                .group("wool_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.BROWN_WOOL) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.BLACK_WOOL, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL)
                .define('D', Items.BLACK_DYE)
                .unlockedBy("has_needed_dye", has(Items.BLACK_DYE))
                .group("wool_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.BLACK_WOOL) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.GRAY_WOOL, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL)
                .define('D', Items.GRAY_DYE)
                .unlockedBy("has_needed_dye", has(Items.GRAY_DYE))
                .group("wool_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.GRAY_WOOL) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.LIGHT_GRAY_WOOL, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL)
                .define('D', Items.LIGHT_GRAY_DYE)
                .unlockedBy("has_needed_dye", has(Items.LIGHT_GRAY_DYE))
                .group("wool_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.LIGHT_GRAY_WOOL) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.WHITE_WOOL, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL)
                .define('D', Items.WHITE_DYE)
                .unlockedBy("has_needed_dye", has(Items.WHITE_DYE))
                .group("wool_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.WHITE_WOOL) + "_from_circle_dyeing"));


        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, Blocks.WHITE_CANDLE, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.CANDLES)
                .define('D', Items.WHITE_DYE)
                .unlockedBy("has_needed_dye", has(Items.WHITE_DYE))
                .group("candle_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.WHITE_CANDLE) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, Blocks.LIGHT_GRAY_CANDLE, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.CANDLES)
                .define('D', Items.LIGHT_GRAY_DYE)
                .unlockedBy("has_needed_dye", has(Items.LIGHT_GRAY_DYE))
                .group("candle_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.LIGHT_GRAY_CANDLE) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, Blocks.GRAY_CANDLE, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.CANDLES)
                .define('D', Items.GRAY_DYE)
                .unlockedBy("has_needed_dye", has(Items.GRAY_DYE))
                .group("candle_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.GRAY_CANDLE) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, Blocks.BLACK_CANDLE, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.CANDLES)
                .define('D', Items.BLACK_DYE)
                .unlockedBy("has_needed_dye", has(Items.BLACK_DYE))
                .group("candle_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.BLACK_CANDLE) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, Blocks.BROWN_CANDLE, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.CANDLES)
                .define('D', Items.BROWN_DYE)
                .unlockedBy("has_needed_dye", has(Items.BROWN_DYE))
                .group("candle_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.BROWN_CANDLE) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, Blocks.PINK_CANDLE, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.CANDLES)
                .define('D', Items.PINK_DYE)
                .unlockedBy("has_needed_dye", has(Items.PINK_DYE))
                .group("candle_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.PINK_CANDLE) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, Blocks.RED_CANDLE, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.CANDLES)
                .define('D', Items.RED_DYE)
                .unlockedBy("has_needed_dye", has(Items.RED_DYE))
                .group("candle_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.RED_CANDLE) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, Blocks.ORANGE_CANDLE, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.CANDLES)
                .define('D', Items.ORANGE_DYE)
                .unlockedBy("has_needed_dye", has(Items.ORANGE_DYE))
                .group("candle_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.ORANGE_CANDLE) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, Blocks.YELLOW_CANDLE, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.CANDLES)
                .define('D', Items.YELLOW_DYE)
                .unlockedBy("has_needed_dye", has(Items.YELLOW_DYE))
                .group("candle_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.YELLOW_CANDLE) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, Blocks.LIME_CANDLE, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.CANDLES)
                .define('D', Items.LIME_DYE)
                .unlockedBy("has_needed_dye", has(Items.LIME_DYE))
                .group("candle_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.LIME_CANDLE) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, Blocks.GREEN_CANDLE, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.CANDLES)
                .define('D', Items.GREEN_DYE)
                .unlockedBy("has_needed_dye", has(Items.GREEN_DYE))
                .group("candle_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.GREEN_CANDLE) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, Blocks.CYAN_CANDLE, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.CANDLES)
                .define('D', Items.CYAN_DYE)
                .unlockedBy("has_needed_dye", has(Items.CYAN_DYE))
                .group("candle_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.CYAN_CANDLE) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, Blocks.BLUE_CANDLE, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.CANDLES)
                .define('D', Items.BLUE_DYE)
                .unlockedBy("has_needed_dye", has(Items.BLUE_DYE))
                .group("candle_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.BLUE_CANDLE) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, Blocks.LIGHT_BLUE_CANDLE, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.CANDLES)
                .define('D', Items.LIGHT_BLUE_DYE)
                .unlockedBy("has_needed_dye", has(Items.LIGHT_BLUE_DYE))
                .group("candle_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.LIGHT_BLUE_CANDLE) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, Blocks.PURPLE_CANDLE, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.CANDLES)
                .define('D', Items.PURPLE_DYE)
                .unlockedBy("has_needed_dye", has(Items.PURPLE_DYE))
                .group("candle_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.PURPLE_CANDLE) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, Blocks.MAGENTA_CANDLE, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.CANDLES)
                .define('D', Items.MAGENTA_DYE)
                .unlockedBy("has_needed_dye", has(Items.MAGENTA_DYE))
                .group("candle_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.MAGENTA_CANDLE) + "_from_circle_dyeing"));

        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.RED_CARPET, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL_CARPETS)
                .define('D', Items.RED_DYE)
                .unlockedBy("has_needed_dye", has(Items.RED_DYE))
                .group("carpet_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.RED_CARPET) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.ORANGE_CARPET, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL_CARPETS)
                .define('D', Items.ORANGE_DYE)
                .unlockedBy("has_needed_dye", has(Items.ORANGE_DYE))
                .group("carpet_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.ORANGE_CARPET) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.YELLOW_CARPET, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL_CARPETS)
                .define('D', Items.YELLOW_DYE)
                .unlockedBy("has_needed_dye", has(Items.YELLOW_DYE))
                .group("carpet_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.YELLOW_CARPET) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.GREEN_CARPET, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL_CARPETS)
                .define('D', Items.GREEN_DYE)
                .unlockedBy("has_needed_dye", has(Items.GREEN_DYE))
                .group("carpet_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.GREEN_CARPET) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.LIME_CARPET, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL_CARPETS)
                .define('D', Items.LIME_DYE)
                .unlockedBy("has_needed_dye", has(Items.LIME_DYE))
                .group("carpet_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.LIME_CARPET) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.LIGHT_BLUE_CARPET, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL_CARPETS)
                .define('D', Items.LIGHT_BLUE_DYE)
                .unlockedBy("has_needed_dye", has(Items.LIGHT_BLUE_DYE))
                .group("carpet_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.LIGHT_BLUE_CARPET) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.BLUE_CARPET, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL_CARPETS)
                .define('D', Items.BLUE_DYE)
                .unlockedBy("has_needed_dye", has(Items.BLUE_DYE))
                .group("carpet_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.BLUE_CARPET) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.PURPLE_CARPET, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL_CARPETS)
                .define('D', Items.PURPLE_DYE)
                .unlockedBy("has_needed_dye", has(Items.PURPLE_DYE))
                .group("carpet_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.PURPLE_CARPET) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.MAGENTA_CARPET, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL_CARPETS)
                .define('D', Items.MAGENTA_DYE)
                .unlockedBy("has_needed_dye", has(Items.MAGENTA_DYE))
                .group("carpet_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.MAGENTA_CARPET) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.PINK_CARPET, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL_CARPETS)
                .define('D', Items.PINK_DYE)
                .unlockedBy("has_needed_dye", has(Items.PINK_DYE))
                .group("carpet_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.PINK_CARPET) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.CYAN_CARPET, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL_CARPETS)
                .define('D', Items.CYAN_DYE)
                .unlockedBy("has_needed_dye", has(Items.CYAN_DYE))
                .group("carpet_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.CYAN_CARPET) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.BROWN_CARPET, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL_CARPETS)
                .define('D', Items.BROWN_DYE)
                .unlockedBy("has_needed_dye", has(Items.BROWN_DYE))
                .group("carpet_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.BROWN_CARPET) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.BLACK_CARPET, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL_CARPETS)
                .define('D', Items.BLACK_DYE)
                .unlockedBy("has_needed_dye", has(Items.BLACK_DYE))
                .group("carpet_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.BLACK_CARPET) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.GRAY_CARPET, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL_CARPETS)
                .define('D', Items.GRAY_DYE)
                .unlockedBy("has_needed_dye", has(Items.GRAY_DYE))
                .group("carpet_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.GRAY_CARPET) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.LIGHT_GRAY_CARPET, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL_CARPETS)
                .define('D', Items.LIGHT_GRAY_DYE)
                .unlockedBy("has_needed_dye", has(Items.LIGHT_GRAY_DYE))
                .group("carpet_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.LIGHT_GRAY_CARPET) + "_from_circle_dyeing"));
        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, Blocks.WHITE_CARPET, 8)
                .pattern("WWW")
                .pattern("WDW")
                .pattern("WWW")
                .define('W', ItemTags.WOOL_CARPETS)
                .define('D', Items.WHITE_DYE)
                .unlockedBy("has_needed_dye", has(Items.WHITE_DYE))
                .group("carpet_circle_dyeing")
                .showNotification(true)
                .save(pWriter, new ResourceLocation(getSimpleRecipeName(Items.WHITE_CARPET) + "_from_circle_dyeing"));


    }

}
